Added missing header files
error: implicit declaration of function 'vTaskDelete' [-Werror=implicit-function-declaration]
error: implicit declaration of function 'usleep'; did you mean 'fseek'? [-Werror=implicit-function-declaration]
usleep(100000);

To resolve these errors header files were added
 
#ifdef ESP_PLATFORM
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#endif

#include <unistd.h>